### ISSUE TITLE
Expose set key method and listen to outside changes

### ISSUE THREAD

**Issue by IgnusG** [brandonpittman/use-idb-keyval#1]
It would be nice if the hook exposed its methods to set key values dynamically.

Let's say I have an upload field and I want to set the key with the file's name to the value of the file.
Currently I have to create the hook and specify the key at the very beginning. So I cannot have a handler that sets that key-value pair dynamically.

I could save the key-value into the DB myself but it would be nice if `use-db-keyval` would:
- Expose its set method since it abstracts DB access
- Listen to DB changes and update the return value of the hook if the DB changes externally - in this case through the call to the exposed set method

**Comment by brandonpittman** [comment]
@IgnusG What kind of API do you envision for this feature?

**Comment by IgnusG** [comment]
For simplicity for now I would probably just suggest exporting [the get, set functions](https://github.com/brandonpittman/use-idb-keyval/blob/master/src/index.js#L3) as named along with the default hook.

It would then be possible to do:
```jsx
import { set } from 'use-idb-keyval';

function Component() {
  return <FileUpload onFile={(fileName, fileContent) => set(fileName, fileContent)} />;
}
```

<br/>

The state should also watch for changes though and update if the DB changes through set. Since IDB does not have any observable support ([yet](https://github.com/WICG/indexed-db-observers/issues/52)) we might work around this using [broadcast channels](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/BroadcastChannel). To keep it simple the broadcast could just signal to every hook that a change for key XY has occured and they would query it themselves
> This is to keep the state between the value from the hook and the value stored (and possibly since modified externally) in sync

If you like the idea @brandonpittman I can open up a PR?

**Comment by brandonpittman** [comment]
@IgnusG Sadly, broadcast channels aren’t supported in Safari.

**Comment by IgnusG** [comment]
We could maybe use `localstorage` and `window.addEventListener('storage')` as a fallback

**Comment by IgnusG** [comment]
We could use a combination of custom events (to notify all use-idb-keyval hooks in the current tab) and the storage event (for cross-tab notification) like so:
https://codesandbox.io/s/relaxed-williams-qkcvu?file=/src/observer.ts

**Comment by IgnusG** [comment]
There's also this polyfill (https://www.npmjs.com/package/broadcast-channel) but I assume it's a bit too heavy given it's 10 times the size of this library

They offer the use of indexedb as a method for the polyfill - which suffers from the same lack of an observable feature 😅
It then simply uses a [read-sleep loop to check the value](https://github.com/pubkey/broadcast-channel/blob/master/src/methods/indexed-db.js). Maybe that would also be sufficient to listen for outside changes?

**Comment by brandonpittman** [comment]
@IgnusG if you wanna put a PR together, I’ll be happy to see it.
